from django import forms

class FilterForm(forms.Form):
	location_target = forms.CharField(max_length=1000, label = "Lokasi Target", widget=forms.TextInput(attrs={'placeholder':'Masukkan lokasi target Anda'}))
	target_type     = forms.ChoiceField(required=True, label = "Jenis Objek Target", choices=[('accounting', 'Accounting'), ('airport', 'Airport'), ('amusement_park', 'Amusement Park'), ('aquarium', 'Aquarium'),
		('art_gallery', 'Art Gallery'), ('atm', 'ATM'), ('bakery', 'Bakery'), ('bank', 'Bank'),
		('bar', 'Bar'), ('beauty_salon', 'Beauty Salon'), ('bicycle_store', 'Bicycle Store'), ('book_store', 'Book Store'),
		('bowling_alley', 'Bowling Alley'), ('bus_station', 'Bus Station'), ('cafe', 'Cafe'), ('campground', 'Campground'),
		('car_dealer', 'Car Dealer'), ('car_rental', 'Car Rental'), ('car_repair', 'Car Repair'), ('car_wash', 'Car Wash'),
		('casino', 'Casino'), ('cemetery', 'Cemetery'), ('church', 'Church'),
		('city_hall', 'City Hall'), ('clothing_store', 'Clothing Store'), ('convenience_store', 'Convenience Store'),
		('courthouse', 'Courthouse'), ('dentist', 'Dentist'), ('department_store', 'Department Store'), ('doctor', 'Doctor'),
		('drugstore', 'Drugstore'), ('electrician', 'Electrician'), ('electronics_store', 'Electronics Store'), ('embassy', 'Embassy'),
		('fire_station', 'Fire Station'), ('florist', 'Florist'), ('funeral_home', 'Funeral Home'), ('furniture_store', 'Furniture Store'),
		('gas_station', 'Gas Station'), ('grocery_or_supermarket', 'Grocery or Supermarket'), ('gym', 'Gym'), ('hair_care', 'Hair Care'),
		('hardware_store', 'Hardware Store'), ('hindu_temple', 'Hindu Temple'), ('home_goods_store', 'Home Goods Store'), ('hospital', 'Hospital'),
		('insurance_agency', 'Insurance Agency'), ('jewelry_store', 'Jewelry Store'), ('laundry', 'Laundry'), ('lawyer', 'Lawyer'),
		('library', 'Library'), ('light_rail_station', 'Light Rail Station'), ('liquor_store', 'Liquor Store'), ('local_government_office', 'Local Government Office'),
		('locksmith', 'Locksmith'), ('lodging', 'Lodging'), ('meal_delivery', 'Meal Delivery'), ('meal_takeaway', 'Meal Takeaway'),
		('mosque', 'Mosque'), ('movie_rental', 'Movie Rental'), ('movie_theater', 'Movie Theater'), ('moving_company', 'Moving Company'),
		('museum', 'Museum'), ('night_club', 'Night Club'), ('painter', 'Painter'), ('park', 'Park'),
		('parking', 'Parking'), ('pet_store', 'Pet Store'), ('pharmacy', 'Pharmacy'), ('physiotherapist', 'Physiotherapist'),
		('plumber', 'Plumber'), ('police', 'Police'), ('post_office', 'Post Office'), ('primary_school', 'Primary School'),
		('real_estate_agency', 'Real Estate Agency'), ('restaurant', 'Restaurant'), ('roofing_contractor', 'Roofing Contractor'), ('rv_park', 'RV Park'),
		('school', 'School'), ('secondary_school', 'Secondary School'), ('shoe_store', 'Shoe Store'), ('shopping_mall', 'Shopping Mall'),
		('spa', 'Spa'), ('stadium', 'Stadium'), ('storage', 'Storage'), ('store', 'Store'),
		('subway_station', 'Subway Station'), ('supermarket', 'Supermarket'), ('synagogue', 'Synagogue'), ('taxi_stand', 'Taxi stand'),
		('tourist_attraction', 'Tourist Attraction'), ('train_station', 'Train Station'), ('transit_station', 'Transit Station'), ('travel_agency', 'Travel Agency'),
		('university', 'University'), ('veterinary_care', 'Veterinary Care'), ('zoo', 'Zoo')])
	radius_target   = forms.IntegerField(label='Radius Objek Target', widget=forms.NumberInput(attrs={'placeholder':'Masukkan radius dalam meter'}))
	#selecting_object = forms.IntegerField(label='Jumlah Fasilitas Dipertimbangkan', widget=forms.NumberInput(attrs={'placeholder':'Masukkan jumlah fasilitas yang dipertimbangkan'}))
	# object_type     = forms.MultipleChoiceField(required=True, label = 'Jenis Fasilitas Sekitar',choices=[('accounting', 'akuntasi'), ('airport', 'bandara'), ('amusement_park', 'taman hiburan'), ('aquarium', 'akuarium'),
	# 	('art_gallery', 'galeri kesenian'), ('atm', 'atm'), ('bakery', 'toko roti'), ('bank', 'bank'),
	# 	('bar', 'bar'), ('beauty_salon', 'salon kecantikan'), ('bicycle_store', 'toko sepeda'), ('book_store', 'toko buku'),
	# 	('bowling_alley', 'arena bowling'), ('bus_station', 'stasiun bus'), ('cafe', 'kafe'), ('campground', 'bumi perkemahan'),
	# 	('car_dealer', 'penjual mobil'), ('car_rental', 'tempat rental mobil'), ('car_repair', 'tempat perbaikan mobil'), ('car_wash', 'tempat cuci mobil'),
	# 	('casino', 'kasino'), ('cemetery', 'kuburan'), ('church', 'gereja'),
	# 	('city_hall', 'city_hall'), ('clothing_store', 'clothing_store'), ('convenience_store', 'convenience_store'),
	# 	('courthouse', 'gedung pengadilan'), ('dentist', 'dokter gigi'), ('department_store', 'department store'), ('doctor', 'dokter'),
	# 	('drugstore', 'toko obat'), ('electrician', 'montir listrik'), ('electronics_store', 'toko elektronik'), ('embassy', 'kedutaan'),
	# 	('fire_station', 'stasiun pemadam kebakaran'), ('florist', 'penjual bunga'), ('funeral_home', 'rumah duka'), ('furniture_store', 'toko furnitur'),
	# 	('gas_station', 'POM bensin'), ('grocery_or_supermarket', 'toko kelontong atau supermarket'), ('gym', 'gym'), ('hair_care', 'perawatan rambut'),
	# 	('hardware_store', 'toko perangkat keras'), ('hindu_temple', 'kuil hindu'), ('home_goods_store', 'toko barang rumah'), ('hospital', 'rumah sakit'),
	# 	('insurance_agency', 'agen asuransi'), ('jewelry_store', 'toko perhiasan'), ('laundry', 'laundry'), ('lawyer', 'pengacara'),
	# 	('library', 'perpustakaan'), ('light_rail_station', 'stasiun kereta ringan'), ('liquor_store', 'toko alkohol'), ('local_government_office', 'kantor pemerintah daerah'),
	# 	('locksmith', 'tukang kunci'), ('lodging', 'penginapan'), ('meal_delivery', 'pengiriman makanan'), ('meal_takeaway', 'takeaway makan'),
	# 	('mosque', 'mesjid'), ('movie_rental', 'persewaan film'), ('movie_theater', 'bioskop'), ('moving_company', 'pindah perusahaan'),
	# 	('museum', 'museum'), ('night_club', 'klub malam'), ('painter', 'pelukis'), ('park', 'taman'),
	# 	('parking', 'parkir'), ('pet_store', 'toko hewan'), ('pharmacy', 'farmasi'), ('physiotherapist', 'ahli fisioterapi'),
	# 	('plumber', 'tukang ledeng'), ('police', 'polisi'), ('post_office', 'kantor Pos'), ('primary_school', 'sekolah dasar'),
	# 	('real_estate_agency', 'agen real estate'), ('restaurant', 'restoran'), ('roofing_contractor', 'kontraktor atap'), ('rv_park', 'taman rv'),
	# 	('school', 'sekolah'), ('secondary_school', 'sekolah menengah'), ('shoe_store', 'toko sepatu'), ('shopping_mall', 'pusat perbelanjaan'),
	# 	('spa', 'spa'), ('stadium', 'stadion'), ('storage', 'penyimpanan'), ('store', 'toko'),
	# 	('subway_station', 'stasiun kereta bawah tanah'), ('supermarket', 'supermarket'), ('synagogue', 'sinagoga'), ('taxi_stand', 'tempat taksi'),
	# 	('tourist_attraction', 'objek wisata'), ('train_station', 'stasiun kereta'), ('transit_station', 'stasiun transit'), ('travel_agency', 'agen perjalanan'),
	# 	('university', 'universitas'), ('veterinary_care', 'perawatan hewan'), ('zoo', 'kebun binatang')])
	object_type     = forms.MultipleChoiceField(required=True, label = 'Jenis Fasilitas Sekitar',choices=[('accounting', 'Accounting'), ('airport', 'Airport'), ('amusement_park', 'Amusement Park'), ('aquarium', 'Aquarium'),
		('art_gallery', 'Art Gallery'), ('atm', 'ATM'), ('bakery', 'Bakery'), ('bank', 'Bank'),
		('bar', 'Bar'), ('beauty_salon', 'Beauty Salon'), ('bicycle_store', 'Bicycle Store'), ('book_store', 'Book Store'),
		('bowling_alley', 'Bowling Alley'), ('bus_station', 'Bus Station'), ('cafe', 'Cafe'), ('campground', 'Campground'),
		('car_dealer', 'Car Dealer'), ('car_rental', 'Car Rental'), ('car_repair', 'Car Repair'), ('car_wash', 'Car Wash'),
		('casino', 'Casino'), ('cemetery', 'Cemetery'), ('church', 'Church'),
		('city_hall', 'City Hall'), ('clothing_store', 'Clothing Store'), ('convenience_store', 'Convenience Store'),
		('courthouse', 'Courthouse'), ('dentist', 'Dentist'), ('department_store', 'Department Store'), ('doctor', 'Doctor'),
		('drugstore', 'Drugstore'), ('electrician', 'Electrician'), ('electronics_store', 'Electronics Store'), ('embassy', 'Embassy'),
		('fire_station', 'Fire Station'), ('florist', 'Florist'), ('funeral_home', 'Funeral Home'), ('furniture_store', 'Furniture Store'),
		('gas_station', 'Gas Station'), ('grocery_or_supermarket', 'Grocery or Supermarket'), ('gym', 'Gym'), ('hair_care', 'Hair Care'),
		('hardware_store', 'Hardware Store'), ('hindu_temple', 'Hindu Temple'), ('home_goods_store', 'Home Goods Store'), ('hospital', 'Hospital'),
		('insurance_agency', 'Insurance Agency'), ('jewelry_store', 'Jewelry Store'), ('laundry', 'Laundry'), ('lawyer', 'Lawyer'),
		('library', 'Library'), ('light_rail_station', 'Light Rail Station'), ('liquor_store', 'Liquor Store'), ('local_government_office', 'Local Government Office'),
		('locksmith', 'Locksmith'), ('lodging', 'Lodging'), ('meal_delivery', 'Meal Delivery'), ('meal_takeaway', 'Meal Takeaway'),
		('mosque', 'Mosque'), ('movie_rental', 'Movie Rental'), ('movie_theater', 'Movie Theater'), ('moving_company', 'Moving Company'),
		('museum', 'Museum'), ('night_club', 'Night Club'), ('painter', 'Painter'), ('park', 'Park'),
		('parking', 'Parking'), ('pet_store', 'Pet Store'), ('pharmacy', 'Pharmacy'), ('physiotherapist', 'Physiotherapist'),
		('plumber', 'Plumber'), ('police', 'Police'), ('post_office', 'Post Office'), ('primary_school', 'Primary School'),
		('real_estate_agency', 'Real Estate Agency'), ('restaurant', 'Restaurant'), ('roofing_contractor', 'Roofing Contractor'), ('rv_park', 'RV Park'),
		('school', 'School'), ('secondary_school', 'Secondary School'), ('shoe_store', 'Shoe Store'), ('shopping_mall', 'Shopping Mall'),
		('spa', 'Spa'), ('stadium', 'Stadium'), ('storage', 'Storage'), ('store', 'Store'),
		('subway_station', 'Subway Station'), ('supermarket', 'Supermarket'), ('synagogue', 'Synagogue'), ('taxi_stand', 'Taxi stand'),
		('tourist_attraction', 'Tourist Attraction'), ('train_station', 'Train Station'), ('transit_station', 'Transit Station'), ('travel_agency', 'Travel Agency'),
		('university', 'University'), ('veterinary_care', 'Veterinary Care'), ('zoo', 'Zoo')])
	radius_object   = forms.IntegerField(label='Radius Fasilitas Sekitar', widget=forms.NumberInput(attrs={'placeholder':'Masukkan radius dalam meter'}))
	rating          = forms.DecimalField(label='Rating',max_digits=2, decimal_places=1, widget=forms.NumberInput(attrs={'placeholder':'Masukkan minimal rating yang diinginkan'}))