# Generated by Django 2.1.5 on 2020-05-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatialskyline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempat', models.CharField(max_length=100)),
            ],
        ),
    ]
